import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,

  // lib/domain is pure: no I/O, no database, no Node built-ins. This is what keeps the §5
  // decision-table suite running in milliseconds instead of needing a database, and it is the
  // single most load-bearing structural rule in the codebase.
  {
    files: ["lib/domain/**/*.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            { group: ["@/lib/db", "@/lib/db/*"], message: "lib/domain must not touch the database." },
            { group: ["@/lib/repo", "@/lib/repo/*"], message: "lib/domain must not touch repositories." },
            { group: ["@/lib/services", "@/lib/services/*"], message: "lib/domain must stay below the service layer." },
            { group: ["@/lib/http", "@/lib/http/*"], message: "lib/domain must not know about HTTP." },
            { group: ["@/lib/shopify", "@/lib/publishing", "@/lib/publishing/*"], message: "lib/domain must not reach the publishing adapter." },
            { group: ["@/lib/storage", "@/lib/storage/*", "@/lib/auth", "@/lib/auth/*", "@/lib/env"], message: "lib/domain must have no I/O or configuration dependency." },
            { group: ["node:*", "fs", "path", "crypto", "postgres", "next", "next/*", "@supabase/*"], message: "lib/domain is pure: no Node built-ins, no drivers, no framework." },
          ],
        },
      ],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `msw init`; committed so the worker is served, but not ours to lint.
    "public/mockServiceWorker.js",
    // Generated coverage output. Gitignored, but eslint flat config does not read .gitignore.
    "coverage/**",
  ]),
]);

export default eslintConfig;
