allowBuilds:
  esbuild: true
  msw: true
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@tanstack/query-core@5.102.1'
  - '@tanstack/react-query@5.102.1'
  - '@tanstack/query-devtools@5.102.1'
  - '@tanstack/react-query-devtools@5.102.1'
