import { type WireSchemaName } from "@/lib/schemas/wire";
import approvalsExactlyTenButHeld from "./approvals.exactly-ten-but-held.json";
import approvalsPendingNew from "./approvals.pending-new.json";
import approvalsSuperseded from "./approvals.superseded.json";
import approvalsZeroApproved from "./approvals.zero-approved.json";
import groupDefault from "./group.default.json";
import historyEmpty from "./history.empty.json";
import historyFivePoints from "./history.five-points.json";
import jobPartialFailure from "./job.partial-failure.json";
import jobQueued from "./job.queued.json";
import jobStalledHeartbeat from "./job.stalled-heartbeat.json";
import productNeedsMargins from "./product.needs-margins.json";
import productNoImages from "./product.no-images.json";
import productSingleSource from "./product.single-source.json";

/**
 * Canned responses for the states the brief predicts will be got wrong.
 *
 * Each file is a whole response body — `{data, meta}` exactly as the endpoint answers — so a test or a
 * story can serve one verbatim through `server.use(...)` without reshaping it. They are generated by
 * `mocks/fixtures/build.ts` from the live handlers; edit the seed and re-run it rather than editing
 * the JSON, or the fixture stops describing anything real.
 *
 * A happy-path-only set would test nothing: every entry here is a row that renders differently from
 * the obvious case, and `note` says which rendering it is guarding.
 */
export interface FixtureEntry {
  name: string;
  /** The endpoint this body came from, for the reader and for regeneration. */
  path: string;
  body: { data: unknown; meta?: unknown };
  schema: WireSchemaName;
  meta?: WireSchemaName;
  note: string;
}

export const FIXTURES: readonly FixtureEntry[] = [
  {
    name: "approvals.pending-new",
    path: "/api/v1/approvals?listing_id=…&status=pending_new",
    body: approvalsPendingNew,
    schema: "ApprovalsListWire",
    meta: "ListMeta",
    note: "`approved_price` is null, so Δ is undefined rather than zero: render 「—」 and a 新產品 badge.",
  },
  {
    name: "approvals.zero-approved",
    path: "/api/v1/approvals?listing_id=…&status=above_threshold",
    body: approvalsZeroApproved,
    schema: "ApprovalsListWire",
    meta: "ListMeta",
    note: "`approved_price` is 0.00 — a real price and the explicit division guard. Also renders 「—」, and it is a different fact from null.",
  },
  {
    name: "approvals.exactly-ten-but-held",
    path: "/api/v1/approvals?listing_id=…&status=above_threshold",
    body: approvalsExactlyTenButHeld,
    schema: "ApprovalsListWire",
    meta: "ListMeta",
    note: "delta_percent 10.0 against a 10.0000 threshold, held because delta_percent_exact is 10.0040. The badge must come from `status`, never from the formatted number.",
  },
  {
    name: "approvals.superseded",
    path: "/api/v1/approvals?listing_id=…&status=superseded",
    body: approvalsSuperseded,
    schema: "ApprovalsListWire",
    meta: "ListMeta",
    note: "A closed-out row: latest wins, so this one carries no action even though it looks pending.",
  },
  {
    name: "product.single-source",
    path: "/api/v1/products/{sku}",
    body: productSingleSource,
    schema: "ProductDetailWire",
    note: "aggregates.source_count is 1: nothing may render 套用於全部 2 個來源 (Gap 31).",
  },
  {
    name: "product.no-images",
    path: "/api/v1/products/{sku}",
    body: productNoImages,
    schema: "ProductDetailWire",
    note: "An empty gallery and a null primary image — the table thumbnail, the dropzone and the publish state all differ.",
  },
  {
    name: "product.needs-margins",
    path: "/api/v1/products/{sku}",
    body: productNeedsMargins,
    schema: "ProductDetailWire",
    note: "Every size 未設定利潤: margin_summary.kind is `none` and each listing's margin fields are null, not zero.",
  },
  {
    name: "history.five-points",
    path: "/api/v1/products/{sku}/history?change_type=listing_price&limit=6",
    body: historyFivePoints,
    schema: "HistoryListWire",
    meta: "HistoryListMetaWire",
    note: "Five points for a six-bar chart: the chart must draw fewer bars, not pad to six.",
  },
  {
    name: "history.empty",
    path: "/api/v1/products/{sku}/history",
    body: historyEmpty,
    schema: "HistoryListWire",
    meta: "HistoryListMetaWire",
    note: "No history at all, and `sizes` is empty too — the 全部尺寸 selector has nothing to offer.",
  },
  {
    name: "job.queued",
    path: "/api/v1/jobs/{id}",
    body: jobQueued,
    schema: "JobWire",
    meta: "JobMetaWire",
    note: "queued with done 0 of 32: renders 排隊中, never `0 / 32`, which reads as stalled.",
  },
  {
    name: "job.partial-failure",
    path: "/api/v1/jobs/{id}",
    body: jobPartialFailure,
    schema: "JobWire",
    meta: "JobMetaWire",
    note: "Screen 4 state E: `succeeded` with failed_count > 0 and per-item SKU, size and reason.",
  },
  {
    name: "job.stalled-heartbeat",
    path: "/api/v1/jobs/{id}?items=all",
    body: jobStalledHeartbeat,
    schema: "JobWire",
    meta: "JobMetaWire",
    note: "running and not advancing, with meta.worker.stale true: 背景服務未運行, not merely slow.",
  },
  {
    name: "group.default",
    path: "/api/v1/groups/{id}",
    body: groupDefault,
    schema: "GroupDetailWire",
    note: "預設分組 with null margins — the state that lets the system default fire — plus Screen 4's scope counts.",
  },
];

export const fixture = (name: string): FixtureEntry => {
  const found = FIXTURES.find((f) => f.name === name);
  if (!found) throw new Error(`no fixture named ${name}`);
  return found;
};
